export const FETCH_EXCHANGE_TODAY_REQUEST = 'FETCH_EXCHANGE_TODAY_REQUEST';
export const FETCH_EXCHANGE_TODAY_SUCCESS = 'FETCH_EXCHANGE_TODAY_SUCCESS';
export const FETCH_EXCHANGE_TODAY_FAILURE = 'FETCH_EXCHANGE_TODAY_FAILURE';

export const FETCH_EXCHANGE_YESTERDAY_REQUEST = 'FETCH_EXCHANGE_YESTERDAY_REQUEST';
export const FETCH_EXCHANGE_YESTERDAY_SUCCESS = 'FETCH_EXCHANGE_YESTERDAY_SUCCESS';
export const FETCH_EXCHANGE_YESTERDAY_FAILURE = 'FETCH_EXCHANGE_YESTERDAY_FAILURE';

export const FETCH_METALS_REQUEST = 'FETCH_METALS_REQUEST';
export const FETCH_METALS_SUCCESS = 'FETCH_METALS_SUCCESS';
export const FETCH_METALS_FAILURE = 'FETCH_METALS_FAILURE';
export const CHANGE_CURRENT_CURRENCY = 'CHANGE_CURRENT_CURRENCY';

export const GOLD = 'XAU';
export const SILVER = 'XAG';